
                <div class="field">
                    <div class="custom-input-box">
                        <input name="email2" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" placeholder="Email"/>
                    </div>
                </div>
            